[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "https://nikhil-vytla.github.io/interactive-blog/*"
to = "https://nikhilvytla.com/:splat"
status = 302
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
